# Generated by Django 3.1.4 on 2021-03-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
