# Generated by Django 3.1.4 on 2021-03-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dev', '0002_dress_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('product_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Dev.dress')),
            ],
        ),
    ]
